<?php
G::LoadClass("plugin");

class authCASPlugin extends PMPlugin
{


    public function authCASPlugin($sNamespace, $sFilename = null)
    {
        $res = parent::PMPlugin($sNamespace, $sFilename);
        $this->sFriendlyName = "authCAS Plugin";
        $this->sDescription  = "Autogenerated plugin for class authCAS";
        $this->sPluginFolder = "authCAS";
        $this->sSetupPage    = "setup";
        $this->iVersion      = 0.1;
        $this->aWorkspaces   = null;
        return $res;
    }

    public function setup()
    {
        if (!defined('PM_SINGLE_SIGN_ON')) {
            define('PM_SINGLE_SIGN_ON', 'authCAS');
        }
        $this->registerTrigger(PM_SINGLE_SIGN_ON, 'casLogin');

        $this->registerPmFunction();
    }

    public function install()
    {
    }

    public function enable()
    {

    }

    public function disable()
    {

    }

}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("authCAS", __FILE__);
